name: Fast Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Fail if takes too long
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install package and ruff
        run: pip install -e . ruff
      
      - name: Python import test
        run: python -c "import fast_intercom_mcp"
      
      - name: Ruff linting (critical errors only)
        run: ruff check . --select E,F --exclude __pycache__
      
      - name: CLI smoke test
        run: python -m fast_intercom_mcp --help